### ISSUE TITLE
Support Sketch 45 plugin update system

### ISSUE THREAD

**Issue by bomberstudios** [vconesa/justinmind-sketch#2]
Hi there!

This is a quick note to remind you that Sketch 45 will include a plugin update system.

It would be awesome if you could add support to it (it's really easy!) before Sketch 45 comes out. Ideally, you should release an update for your plugin while we're still in Sketch 44, so your users will have a nice & easy experience when 45 is released.

For more details, please check http://sketchplugins.com/d/229-updating-plugins and http://developer.sketchapp.com/introduction/updating-plugins/

Thanks in advance!

**Comment by vconesa** [comment]
We've configured the plugin update system. Is there a way to make sure we did it right?

**Comment by bomberstudios** [comment]
I'll test it for you right away : )

**Comment by bomberstudios** [comment]
It _almost_ works. I'm sending you a PR to fix a small typo : )

**Comment by bomberstudios** [comment]
(You'll need to also update the ZIP in the repo, BTW)

**Comment by vconesa** [comment]
Done. Thanks so much!!!


*Victor Conesa *| Product Manager
victor.conesa@justinmind.com
www.justinmind.com
