### ISSUE TITLE
Export failing: Sketch 47.1

### ISSUE THREAD

**Issue by mollycr** [vconesa/justinmind-sketch#7]
Hello!

I'm trying to export some screens from sketch and it's failing at the end.

I'm getting the error message: "ObjC method arrayWithObjects: requires 1 argument, but JavaScript passed 4 arguments"

Let me know if I can provide any other information.

**Comment by adc358** [comment]
I am having the same problem .

**Comment by vconesa** [comment]
It should be fixed in the latest update of the plugin
